Require slack token in update script

diff --git a/run-update b/run-update
--- a/run-update
+++ b/run-update
@@ -1,5 +1,10 @@
 #!/bin/bash -e
 
+if [[ -z "$1" ]]; then
+  echo "Slack Token is required as the first argument"
+  exit 1
+fi
+
 docker build -t slack-status-time . > /dev/null 2>&1
 
 docker run -e "SLACK_TOKEN=$1" -e "TZ=${TZ:-America/New_York}" slack-status-time
